### ISSUE TITLE
ESC key should close search dialogue

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/next-wordpress-starter#50]
When making a search, we should a dropdown with autocomplete results

If that dropdown is open and someone clicks outside of that box, we clear the search and close the modal

If someone presses ESC while that dropdown is open, we should similarly cleare the search and close the modal

we can use the document onClick functionality as an example of how to implement in Nav.js

`addDocumentOnClick`, `removeDocumentOnClick`, and `handleOnDocumentClick`

**Comment by itsthecheat** [comment]
Hello! If this is available I'd be happy to work on it

**Comment by colbyfayock** [comment]
@itsthecheat all yours!

**Comment by jatin-rathee** [comment]
@colbyfayock can I work on this one?

**Comment by colbyfayock** [comment]
hey @jatin-rathee I believe @itsthecheat is working on it, but if they don't end up getting to it then it's all yours

**Comment by jatin-rathee** [comment]
@colbyfayock  are you sure @itsthecheat  is working on this one?

**Comment by colbyfayock** [comment]
i was gonna check in after the 7 day mark :)

@itschecheat if we dont hear from you by tomorrow that you've been actively working on it I'm going to let @jatin-rathee have at it

**Comment by colbyfayock** [comment]
hey @jatin-rathee it's all yours :)

**Comment by jatin-rathee** [comment]
@colbyfayock I am getting some error while setup, can you tell what comes in `.env.local`?

**Comment by colbyfayock** [comment]
as of now you only need your wordpress host `WORDPRESS_HOST`

https://github.com/colbyfayock/next-wordpress-starter#environment

**Comment by jatin-rathee** [comment]
```
Server Error
Error: Unexpected token < in JSON at position 0

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

Getting this when i gave the address of local wordpress instance. @colbyfayock Can you help?

**Comment by colbyfayock** [comment]
hey @jatin-rathee i'll try to give you a hand later after work - for now, can you open a new issue with a title that reflects the error so others can find it too with the answer?

**Comment by jatin-rathee** [comment]
@colbyfayock I think there is something wrong with my local setup. 

`WORDPRESS_HOST="http://localhost/wordpress/"`

Is this fine?

**Comment by GuilleAngulo** [comment]
hey @jatin-rathee have you tried using your IP instead of localhost? Also you need to remove last trailing slash, to allow graphql calls be properly made (it is add inside the code /grapqhl to the variable).

`WORDPRESS_HOST="http://<your_ip>/wordpress"`

I hope that solves it

**Comment by colbyfayock** [comment]
@GuilleAngulo  is that a confirmed issue? i can open a ticket for someone (or me) to fix that, we shouldn't care if there's a `/` at the end to avoid issues like this

**Comment by GuilleAngulo** [comment]
@colbyfayock Yes, checked just now and seems like is breaking with the trailingslash, it adds double _//._ Also this is related to #79.

![issue](https://user-images.githubusercontent.com/50624358/97354696-929d7e00-1874-11eb-81f8-36d1f6777ba4.png)

**Comment by GuilleAngulo** [comment]
I can send a PR if you want. Creating a new util function on site.js lib to remove last trailing slash on a string, and use it before setting the env variable at next.config.js

**Comment by colbyfayock** [comment]
cool a PR would be great! another thought is to maybe use `path.join()`, though not sure if that works with a url 🤔  but whatever you think works, thanks. ill makke an issue an assign it to ya

**Comment by GuilleAngulo** [comment]
It seems like won't work properly using path module. Also checked using [url module](https://nodejs.org/api/url.html), but didn't find a proper way to remove the trailing slash if is coming already with the behind pathname...

**Comment by colbyfayock** [comment]
@jatin-rathee if you pull in the latest changes, it should fix the trailing slash issue. curious if that's the issue you're facing

**Comment by jatin-rathee** [comment]
@colbyfayock @GuilleAngulo sorry but im still getting same error

`[Feed] Failed to fetch posts from http://localhost/wordpress/graphql: Error: Unexpected token < in JSON at position 0`

**Comment by colbyfayock** [comment]
@jatin-rathee can you please open a new Issue for this as it's unrelated to this Issue?

**Comment by GuilleAngulo** [comment]
@jatin-rathee Instead of using `localhost` try using your machine IP `WORDPRESS_HOST="http://<your_ip>/wordpress`. Not sure yet why with a local instance using localhost does not work...

**Comment by jatin-rathee** [comment]
@GuilleAngulo changing localhost with ip didn't work for me

**Comment by jatin-rathee** [comment]
@colbyfayock opened new issue #86

**Comment by jatin-rathee** [comment]
@colbyfayock fixed this in #87 Please review

**Comment by colbyfayock** [comment]
thanks @jatin-rathee!
